name: Unit Tests
on: push
jobs:
  terraform-tests:
    name: Run Terraform Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4
        with:
          terraform_version: "1.7"

      - run: terraform init
      - run: terraform test
